####

POST http://localhost:5000/api/user/login HTTP/1.1
authorization: Bearer eyJhbG.eyJlbWFpbCII6MTY1MjI4NjgzN30.xkXNNho-MxECZsJXCIU

#####

GET http://localhost:5000/api/user/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhYUB0ZXN0LmNvbSIsImxvZ2luIjoiaXN3MCIsImlhdCI6MTY4NDQ5MDM2NCwiZXhwIjoxNzE-2MDI_2MzY0fQ.b17AZf22Ah2WXqMHxugKd7WvNLsMEig9e3tTt1bZPyg HTTP/1.1

###